language: node_js

sudo: required

cache:
  yarn: true
  directories:
    - ~/.cache
  override:
    - yarn install --frozen-lockfile

defaults: &deploySite
  install:
    - ./scripts/bin/docker-install.sh
  script:
    - ./scripts/bin/docker-publish-docs.sh

defaults: &test
  install:
    - ./scripts/bin/docker-install.sh
  env:
    - NODE_ENV=test
    - STAGE_NAME=4x-electron
  script:
    - ./scripts/bin/docker-test.sh

jobs:
  include:
    - stage: Verify
      <<: *test
    - stage: Verify
      install:
        - ./scripts/bin/docker-install.sh
      script:
        - ./scripts/bin/docker-lint.sh

    - stage: 'Deploy Preview of Docs Site'
      if: type = pull_request
      env:
        - SHA=$TRAVIS_PULL_REQUEST_SHA
        - NODE_ENV=production
      <<: *deploySite

    - stage: 'Publish to NPM'
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
      install:
        - ./scripts/bin/docker-install.sh
      script:
        - echo 'This is empty for now'

    - stage: 'Publish to NPM (next)'
      if: branch = next AND type = push
      env:
        - NODE_ENV=production
        - NEXT=1
      install:
        - ./scripts/bin/docker-install.sh
      script:
        - ./scripts/bin/docker-publish.sh

    - stage: 'Deploy Production Docs Site'
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
        - SHA=$TRAVIS_COMMIT
        - PROD=1
      <<: *deploySite

    - stage: 'Deploy Production Docs Site (next)'
      if: branch = next AND type = push
      env:
        - NODE_ENV=production
        - SHA=$TRAVIS_COMMIT
        - PROD=1
      <<: *deploySite
