language: node_js

services:
  - docker

sudo: required

cache:
  yarn: true
  directories:
    - ~/.cache
  override:
    - yarn install --frozen-lockfile

defaults: &deploySite
  install:
    - ./scripts/bin/docker-install.sh
  script:
    - ./scripts/bin/docker-publish-docs.sh

jobs:
  include:
    - stage: 'Verify'
      env:
        - NODE_ENV: test
      install:
        - ./scripts/bin/docker-install.sh
        - yarn add -W cypress --dev
      script:
        - yarn test:e2e:ci

    - stage: 'Deploy Preview of Docs Site'
      if: type = pull_request
      env:
        - SHA=$TRAVIS_PULL_REQUEST_SHA
        - NODE_ENV=development
      <<: *deploySite

    - stage: 'Publish to NPM'
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
      install:
        - ./scripts/bin/docker-install.sh
      script:
        - echo 'This is empty for now'

    - stage: 'Deploy Production Docs Site'
      if: branch = master AND type = push
      env:
        - SHA=$TRAVIS_COMMIT
        - PROD=1
      <<: *deploySite
