language: node_js

sudo: required

cache:
  yarn: true
  directories:
    - ~/.cache
  override:
    - yarn install --frozen-lockfile

defaults: &deploySite
  install:
    - ./scripts/bin/ci-install.sh
  script:
    - node ./scripts/tasks/publish-docs.js

jobs:
  include:
    - stage: Verify
      install:
        - ./scripts/bin/ci-install.sh
      script:
        - ./scripts/bin/execute.lint.sh

    - stage: Verify
      if: type = push
      install:
        - ./scripts/bin/ci-install.sh
      env:
        - NODE_ENV=test
        - SHA=$TRAVIS_COMMIT
      script:
        - node ./scripts/tasks/test.js

    - stage: Verify
      if: type = pull_request
      install:
        - ./scripts/bin/ci-install.sh
      env:
        - NODE_ENV=test
        - SHA=$TRAVIS_PULL_REQUEST_SHA
      script:
        - node ./scripts/tasks/test.js

    - stage: 'Deploy Preview of Docs Site'
      if: type = pull_request
      env:
        - SHA=$TRAVIS_PULL_REQUEST_SHA
      <<: *deploySite

    - stage: 'Publish to NPM'
      if: branch = master AND type = push
      install:
        - ./scripts/bin/ci-install.sh
      script:
        - node ./scripts/tasks/publish.js

    - stage: 'Publish to NPM (next)'
      if: branch = next AND type = push
      env:
        - NEXT=1
      install:
        - ./scripts/bin/ci-install.sh
      script:
        - node ./scripts/tasks/publish.js

    - stage: 'Deploy Production Docs Site'
      if: branch = master AND type = push
      env:
        - SHA=$TRAVIS_COMMIT
        - PROD=1
      <<: *deploySite

    - stage: 'Deploy Production Docs Site (next)'
      if: branch = next AND type = push
      env:
        - SHA=$TRAVIS_COMMIT
        - PROD=1
      <<: *deploySite
